package HealthMonitorMng.hbm.base;

/**
 * Model generated by MyEclipse Persistence Tools
 */

public class AnalysisResult implements java.io.Serializable {

	/**
	 * serialVersionUID
	 *
	 * @since Ver 1.1
	 */

	private static final long serialVersionUID = -2771170574300962441L;
	// Fields

	private String id;
	private String userid;
	private String tebing;
	private String qiyu;
	private String heping;
	private String yangxu;
	private String yinxu;
	private String qixu;
	private String tanshi;
	private String shire;
	private String xueyu;
	private String name;
	private String mail;

	/**
	 * id
	 *
	 * @return the id
	 * @since CodingExample Ver 1.0
	 */

	public String getId() {
		return id;
	}

	/**
	 * id
	 *
	 * @param id
	 *            the id to set
	 * @since CodingExample Ver 1.0
	 */

	public void setId(String id) {
		this.id = id;
	}

	/**
	 * userid
	 *
	 * @return the userid
	 * @since CodingExample Ver 1.0
	 */

	public String getUserid() {
		return userid;
	}

	/**
	 * userid
	 *
	 * @param userid
	 *            the userid to set
	 * @since CodingExample Ver 1.0
	 */

	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * yangxu
	 *
	 * @return the yangxu
	 * @since CodingExample Ver 1.0
	 */

	public String getYangxu() {
		return yangxu;
	}

	/**
	 * yangxu
	 *
	 * @param yangxu
	 *            the yangxu to set
	 * @since CodingExample Ver 1.0
	 */

	public void setYangxu(String yangxu) {
		this.yangxu = yangxu;
	}

	/**
	 * yinxu
	 *
	 * @return the yinxu
	 * @since CodingExample Ver 1.0
	 */

	public String getYinxu() {
		return yinxu;
	}

	/**
	 * yinxu
	 *
	 * @param yinxu
	 *            the yinxu to set
	 * @since CodingExample Ver 1.0
	 */

	public void setYinxu(String yinxu) {
		this.yinxu = yinxu;
	}

	/**
	 * qixu
	 *
	 * @return the qixu
	 * @since CodingExample Ver 1.0
	 */

	public String getQixu() {
		return qixu;
	}

	/**
	 * qixu
	 *
	 * @param qixu
	 *            the qixu to set
	 * @since CodingExample Ver 1.0
	 */

	public void setQixu(String qixu) {
		this.qixu = qixu;
	}

	/**
	 * tanshi
	 *
	 * @return the tanshi
	 * @since CodingExample Ver 1.0
	 */

	public String getTanshi() {
		return tanshi;
	}

	/**
	 * tanshi
	 *
	 * @param tanshi
	 *            the tanshi to set
	 * @since CodingExample Ver 1.0
	 */

	public void setTanshi(String tanshi) {
		this.tanshi = tanshi;
	}

	/**
	 * shire
	 *
	 * @return the shire
	 * @since CodingExample Ver 1.0
	 */

	public String getShire() {
		return shire;
	}

	/**
	 * shire
	 *
	 * @param shire
	 *            the shire to set
	 * @since CodingExample Ver 1.0
	 */

	public void setShire(String shire) {
		this.shire = shire;
	}

	/**
	 * xueyu
	 *
	 * @return the xueyu
	 * @since CodingExample Ver 1.0
	 */

	public String getXueyu() {
		return xueyu;
	}

	/**
	 * xueyu
	 *
	 * @param xueyu
	 *            the xueyu to set
	 * @since CodingExample Ver 1.0
	 */

	public void setXueyu(String xueyu) {
		this.xueyu = xueyu;
	}

	/**
	 * tebing
	 *
	 * @return the tebing
	 * @since CodingExample Ver 1.0
	 */

	public String getTebing() {
		return tebing;
	}

	/**
	 * tebing
	 *
	 * @param tebing
	 *            the tebing to set
	 * @since CodingExample Ver 1.0
	 */

	public void setTebing(String tebing) {
		this.tebing = tebing;
	}

	/**
	 * qiyu
	 *
	 * @return the qiyu
	 * @since CodingExample Ver 1.0
	 */

	public String getQiyu() {
		return qiyu;
	}

	/**
	 * qiyu
	 *
	 * @param qiyu
	 *            the qiyu to set
	 * @since CodingExample Ver 1.0
	 */

	public void setQiyu(String qiyu) {
		this.qiyu = qiyu;
	}

	/**
	 * heping
	 *
	 * @return the heping
	 * @since CodingExample Ver 1.0
	 */

	public String getHeping() {
		return heping;
	}

	/**
	 * heping
	 *
	 * @param heping
	 *            the heping to set
	 * @since CodingExample Ver 1.0
	 */

	public void setHeping(String heping) {
		this.heping = heping;
	}

	/**
	 * name
	 *
	 * @return the name
	 * @since CodingExample Ver 1.0
	 */

	public String getName() {
		return name;
	}

	/**
	 * name
	 *
	 * @param name
	 *            the name to set
	 * @since CodingExample Ver 1.0
	 */

	public void setName(String name) {
		this.name = name;
	}

	/**
	 * mail
	 *
	 * @return the mail
	 * @since CodingExample Ver 1.0
	 */

	public String getMail() {
		return mail;
	}

	/**
	 * mail
	 *
	 * @param mail
	 *            the mail to set
	 * @since CodingExample Ver 1.0
	 */

	public void setMail(String mail) {
		this.mail = mail;
	}

}