package HealthMonitorMng.hbm.base;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import HealthMonitorMng.util.JsonDateOnlySerializer;

/**
 * Model generated by MyEclipse Persistence Tools
 */

public class PushMessage implements java.io.Serializable {

	private static final long serialVersionUID = -5140962891915945371L;
	/**
	 * 
	 */
	// Fields

	private String id;
	private String title;
	private String textValue;
	private Date createTime;

	public PushMessage() {

	}

	/**
	 * id
	 *
	 * @return the id
	 * @since CodingExample Ver 1.0
	 */

	public String getId() {
		return id;
	}

	/**
	 * id
	 *
	 * @param id
	 *            the id to set
	 * @since CodingExample Ver 1.0
	 */

	public void setId(String id) {
		this.id = id;
	}

	/**
	 * title
	 *
	 * @return the title
	 * @since CodingExample Ver 1.0
	 */

	public String getTitle() {
		return title;
	}

	/**
	 * title
	 *
	 * @param title
	 *            the title to set
	 * @since CodingExample Ver 1.0
	 */

	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * createTime
	 *
	 * @return the createTime
	 * @since CodingExample Ver 1.0
	 */
	@JsonSerialize(using = JsonDateOnlySerializer.class)
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * createTime
	 *
	 * @param createTime
	 *            the createTime to set
	 * @since CodingExample Ver 1.0
	 */

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * textValue
	 *
	 * @return the textValue
	 * @since CodingExample Ver 1.0
	 */

	public String getTextValue() {
		return textValue;
	}

	/**
	 * textValue
	 *
	 * @param textValue
	 *            the textValue to set
	 * @since CodingExample Ver 1.0
	 */

	public void setTextValue(String textValue) {
		this.textValue = textValue;
	}
}