package HealthMonitorMng.hbm.base;

/**
 * Model generated by MyEclipse Persistence Tools
 */

public class Template implements java.io.Serializable {

	private static final long serialVersionUID = -5140962891915945371L;
	/**
	 * 
	 */
	// Fields

	private String id;
	private String templateName;
	private String templateJson;

	public Template() {

	}

	/**
	 * id
	 *
	 * @return the id
	 * @since CodingExample Ver 1.0
	 */

	public String getId() {
		return id;
	}

	/**
	 * id
	 *
	 * @param id
	 *            the id to set
	 * @since CodingExample Ver 1.0
	 */

	public void setId(String id) {
		this.id = id;
	}

	/**
	 * templateName
	 *
	 * @return the templateName
	 * @since CodingExample Ver 1.0
	 */

	public String getTemplateName() {
		return templateName;
	}

	/**
	 * templateName
	 *
	 * @param templateName
	 *            the templateName to set
	 * @since CodingExample Ver 1.0
	 */

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	/**
	 * templateJson
	 *
	 * @return the templateJson
	 * @since CodingExample Ver 1.0
	 */

	public String getTemplateJson() {
		return templateJson;
	}

	/**
	 * templateJson
	 *
	 * @param templateJson
	 *            the templateJson to set
	 * @since CodingExample Ver 1.0
	 */

	public void setTemplateJson(String templateJson) {
		this.templateJson = templateJson;
	}

}