package HealthMonitorMng.hbm.base.background;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model generated by MyEclipse Persistence Tools
 */

public class Organization implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7378221319554966093L;
	// Fields

	private String id;
	private String name;
	private Date createTime;
	private Set organizationUsers = new HashSet(0);

	public Organization() {

	}

	/** minimal constructor */
	public Organization(String organizationID) {
		this.id = organizationID;
	}

	public Organization(String id, String name, Set organizationUsers) {
		this.id = id;
		this.name = name;
		this.organizationUsers = organizationUsers;
	}

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime
	 *            the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the organizationUsers
	 */
	public Set getOrganizationUsers() {
		return organizationUsers;
	}

	/**
	 * @param organizationUsers
	 *            the organizationUsers to set
	 */
	public void setOrganizationUsers(Set organizationUsers) {
		this.organizationUsers = organizationUsers;
	}

}