package HealthMonitorMng.model;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import HealthMonitorMng.util.JsonDateOnlySerializer;

/**
 * Model generated by MyEclipse Persistence Tools
 */

public class DepartmentModel {

	private String id;
	private String name;
	private Date createTime;

	public DepartmentModel() {

	}

	/** minimal constructor */
	public DepartmentModel(String departmentID) {
		this.id = departmentID;
	}

	public DepartmentModel(String id, String name, Date createTime) {
		this.id = id;
		this.name = name;
		this.createTime = createTime;
	}

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the createTime
	 */
	@JsonSerialize(using = JsonDateOnlySerializer.class)
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime
	 *            the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}